### PR TITLE
feat: add image support in chat

### PR DESCRIPTION
**Pull request by kevin-on**
# Image Support for Chat Messages

This PR adds support for image uploads and display in chat messages, enabling users to include images in their conversations.

## Key Changes

- Added image upload button in chat input
- Image paste support via `ImagePastePlugin`
- Preview of uploaded images in the chat interface
- Add support for handling image content in messages across LLM providers

### CODE REVIEW

**Review by glowingjade — COMMENTED** [review]
This section is getting too crowded. How about simplifying it by displaying only the icons without labels and using tooltips to inform users of each icon's purpose?

Screenshot 2024-11-25 at 3 27 06 PM

**Comment by glowingjade** [comment]
It looks like the drag and drop feature for images isn't working. Could you please take a look at that?

**Comment by kevin-on** [comment]
> It looks like the drag and drop feature for images isn't working. Could you please take a look at that?

I didn't implement drag and drop feature yet. I'll check it out.

**Comment by kevin-on** [comment]
Now model names are truncated like:
image

**Review by glowingjade — APPROVED** [review]

**Pull request merged**
